name: deploy
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: launchpad

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm clean-install
      - run: npm run test
      - run: npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: launchpad/dist
      - uses: actions/deploy-pages@v4
