name: deploy
on: [push, workflow_dispatch]
jobs:

 update:
    runs-on: ubuntu-latest
    steps:
      - run: apt update -y
  
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5
      - run: echo "Hello"

  say-bye:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5
      - run: echo "Bye"